---
- hosts: all
  vars_files:
    - ~/winpassword.yml
  tasks:
  - name: Ping
    ping:
    when: ansible_system == "Linux"
    ignore_errors: True

  - name: Winping
    win_ping:
    when: ansible_system == "Win32NT"
    ignore_errors: True