---
- hosts: tag_userx
  remote_user: "user"
  become: "yes"
  vars:
    websiteheader: "Ansible Playbook in vmware"
    websiteauthor: "Ansible trainee"

  tasks:
  - name: Install Apache
    dnf:
     name: httpd
     state: latest

  - name: Enable Apache
    systemd:
     name: httpd
     enabled: yes
     state: started

  - name: Allow http in firewall
    firewalld:
     service: http
     permanent: true
     state: enabled
     immediate: yes
    notify:
      - reload firewall

  - name: Add index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root

  handlers:
  - name: reload firewall
    systemd:
      name: firewalld
      state: reloaded